version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pruebatecnica-net

  postgres-cliente:
    image: postgres:15
    environment:
      POSTGRES_DB: cliente_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cliente_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cliente-db-data:/var/lib/postgresql/data
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./seed_clientes.sql:/docker-entrypoint-initdb.d/02_seed.sql
    networks:
      - pruebatecnica-net

  postgres-cuenta:
    image: postgres:15
    environment:
      POSTGRES_DB: cuenta_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cuenta_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cuenta-db-data:/var/lib/postgresql/data
      - ./seed_cuentas.sql:/docker-entrypoint-initdb.d/02_seed.sql
    networks:
      - pruebatecnica-net

  cliente-service:
    build:
      context: ./cliente-service
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-cliente:5432/cliente_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      postgres-cliente:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - pruebatecnica-net

  cuenta-service:
    build:
      context: ./cuenta-service
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-cuenta:5432/cuenta_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8081
    depends_on:
      postgres-cuenta:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - pruebatecnica-net

volumes:
  cliente-db-data:
  cuenta-db-data:

networks:
  pruebatecnica-net:
    driver: bridge
