spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientesdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672

app:
  rabbitmq:
    exchange: cliente.exchange
    routing-key: cliente.created
    queue: cliente.event.queue
